### ISSUE TITLE
CompositeMessageLookup are not cleared when used with `Localizations.override(...)`

### ISSUE THREAD

**Issue by qwert2603** [Innim/flutter_multiple_localization#1]
Hello! If we use `Localizations.override(delegates: [SomeLocalizationsDelegate(), ...])` somewhere in widgets tree, then `initializeMessages` (and `_MultipleLocalizationLookup.addLocale`) will be called every time, when that widget rebuilds. And that will lead to adding more and more `CompositeMessageLookup` to list `_MultipleLocalizationLookup._lookups`.

I suppose, we need clear previous `CompositeMessageLookup` from `_MultipleLocalizationLookup._lookups`, but there is no straight way to find out when `CompositeMessageLookup` is being replaced.

**Comment by greymag** [comment]
You are right, I did not consider this. I will take a look. Thanks for the report 👍
