### ISSUE TITLE
migrate to nnbd

### ISSUE THREAD

**Issue by nt4f04uNd** [Innim/flutter_multiple_localization#5]
intl has already migrated, so migration can be easily done

**Comment by greymag** [comment]
Hey! Just published [prerelease version](https://pub.dev/packages/multiple_localization/versions/0.2.0-nullsafety.0). It's in separate branch [`null-safety`](https://github.com/Innim/flutter_multiple_localization/tree/null-safety) on repo.

But there is the problem with using intl with null-safety - generation doesn't work properly. See [the issue](https://github.com/dart-lang/i18n/issues/563) in [intl_translation](https://github.com/dart-lang/intl_translation).
