### ISSUE TITLE
dependency to intl 0.17 required

### ISSUE THREAD

**Issue by fvisticot** [Innim/flutter_multiple_localization#6]
Because multiple_localization 0.1.1 depends on intl ^0.16.0 and no versions of multiple_localization match >0.1.1 <0.2.0, multiple_localization ^0.1.1 requires intl ^0.16.0.

So, because myapp depends on both intl ^0.17.0 and multiple_localization ^0.1.1, version solving failed.

Can you please update the dependency to 0.17 ?

**Comment by greymag** [comment]
Hey!

Just use [pre-release version](https://pub.dev/packages/multiple_localization/versions/0.2.0-nullsafety.0).

```
multiple_localization: ^0.2.0-nullsafety.0
```

It's depends on `intl: ^0.17.0`. 

This version will be released as stable in a week.

**Comment by greymag** [comment]
Released in [stable](https://pub.dev/packages/multiple_localization). Sorry for delay
